# Generated by Django 3.2 on 2022-06-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaHud', '0004_auto_20220617_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
