# Generated by Django 3.2 on 2022-06-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaHud', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
