# Generated by Django 3.2 on 2022-06-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaHud', '0006_auto_20220618_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
