# Generated by Django 3.2 on 2022-06-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaHud', '0007_auto_20220618_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
